server:
  port: 8080

spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    username: local_server
    password: local_server
    url: jdbc:postgresql://localhost:5432/besthack22